#!/usr/bin/env python3
"""Emit LEARNING-PATH.md — every track topologically sorted by prerequisite,
then a module-level order within each track. Answers "what do I study next,
and what must come before it".

Run: python app/learning_path.py
"""
from __future__ import annotations
import glob, json, pathlib
from collections import defaultdict

ROOT = pathlib.Path(__file__).resolve().parent.parent
C = json.loads((ROOT / "app/data/curriculum.json").read_text(encoding="utf-8"))
tracks = {t["id"]: t for t in C["tracks"]}


def written(t) -> set[str]:
    files = {pathlib.Path(p).stem for p in glob.glob(str(ROOT / t["dir"] / "*.md"))}
    return {m["slug"] for m in t["modules"] if any(f.endswith(m["slug"]) for f in files)}


def toposort() -> list[str]:
    """Kahn's algorithm. Ties broken by (phase, sprint-bearing, hours) so the
    interview-critical work surfaces first among equally-unblocked tracks."""
    indeg = {tid: 0 for tid in tracks}
    adj = defaultdict(list)
    for tid, t in tracks.items():
        for p in t.get("prereqs", []):
            if p in tracks:
                adj[p].append(tid)
                indeg[tid] += 1

    def rank(tid):
        t = tracks[tid]
        has_sprint = any("sprint" in m["tags"] for m in t["modules"])
        return (0 if t["phase"] == "A" else 1, 0 if has_sprint else 1, -t["hours"], tid)

    ready = sorted([t for t, d in indeg.items() if d == 0], key=rank)
    out = []
    while ready:
        tid = ready.pop(0)
        out.append(tid)
        for nxt in adj[tid]:
            indeg[nxt] -= 1
            if indeg[nxt] == 0:
                ready.append(nxt)
        ready.sort(key=rank)
    if len(out) != len(tracks):
        cyc = sorted(set(tracks) - set(out))
        raise SystemExit(f"PREREQUISITE CYCLE among: {cyc}")
    return out


def main() -> None:
    order = toposort()
    L = ["# Learning path", "",
         "> Generated by `app/learning_path.py`. Tracks are topologically sorted by",
         "> prerequisite; within a tier, interview-critical work comes first.", "",
         "**Read this top to bottom.** Nothing below depends on something further down.", ""]

    # tier = longest prerequisite chain depth
    depth = {}
    for tid in order:
        pr = [p for p in tracks[tid].get("prereqs", []) if p in tracks]
        depth[tid] = 0 if not pr else max(depth[p] for p in pr) + 1

    by_tier = defaultdict(list)
    for tid in order:
        by_tier[depth[tid]].append(tid)

    for tier in sorted(by_tier):
        label = "no prerequisites — start anywhere here" if tier == 0 else \
                f"unlocked after tier {tier - 1}"
        L += [f"## Tier {tier} — {label}", "",
              "| Track | Modules | Hours | Phase | Requires |", "|---|---|---|---|---|"]
        for tid in by_tier[tier]:
            t = tracks[tid]
            w = len(written(t)); n = len(t["modules"])
            req = ", ".join(t["prereqs"]) or "—"
            mark = " ✅" if w == n else f" ({w}/{n})"
            L.append(f"| {t['icon']} **{t['title']}**{mark} | {n} | {t['hours']} | {t['phase']} | {req} |")
        L.append("")

    L += ["## Module order within each track", "",
          "Modules are listed in their authored order, which already respects",
          "internal dependencies. `sprint` modules are the interview-critical subset.", ""]
    for tid in order:
        t = tracks[tid]
        done = written(t)
        L.append(f"### {t['icon']} {t['title']}  ({t['id']})")
        for m in t["modules"]:
            tags = []
            if "sprint" in m["tags"]:
                tags.append("sprint")
            if "critical" in m["tags"]:
                tags.append("critical")
            suffix = f"  _{' · '.join(tags)}_" if tags else ""
            box = "x" if m["slug"] in done else " "
            L.append(f"- [{box}] {m['title']} — {m['hours']}h{suffix}")
        L.append("")

    (ROOT / "LEARNING-PATH.md").write_text("\n".join(L), encoding="utf-8")
    tot_w = sum(len(written(t)) for t in tracks.values())
    print(f"LEARNING-PATH.md written · {len(order)} tracks in {max(by_tier)+1} tiers · "
          f"{tot_w}/{C['totals']['modules']} modules done")


if __name__ == "__main__":
    main()
