#!/usr/bin/env python3
"""Generate progress/CONFIRM-CHECKLIST.md — every `[CONFIRM: ]` placeholder in
the curriculum that needs the student's real numbers.

No agent can fill these: they are the student's actual team sizes, measured
latencies, and real incident outcomes. An invented number in a STAR story is
exactly what a hiring manager catches on the follow-up. This file turns the
scattered placeholders into one sitting of work.

Re-run after filling entries in (it regenerates from scratch)."""
from __future__ import annotations

import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "progress" / "CONFIRM-CHECKLIST.md"
PAT = re.compile(r"\[CONFIRM:?\s*([^\]]*)\]")

groups: dict[str, list[tuple[int, str]]] = {}
total = 0
for md in sorted(ROOT.glob("curriculum/**/*.md")):
    for ln, line in enumerate(md.read_text(encoding="utf-8").splitlines(), 1):
        for m in PAT.finditer(line):
            rel = str(md.relative_to(ROOT)).replace("\\", "/")
            groups.setdefault(rel, []).append((ln, m.group(1).strip() or "(bare [CONFIRM] — find the sentence/table cell it sits in)"))
            total += 1

lines = [
    "# CONFIRM checklist — facts only you can fill",
    "",
    f"> Auto-generated by `scripts/gen_confirm_checklist.py` · **{total} open items**",
    ">",
    "> These are placeholders in the resume-defence block where a module needs YOUR",
    "> real numbers — team sizes, how the 89% ETL cut was measured, what actually",
    "> happened in the ClickHouse OOM. No agent can fill them. An invented number in",
    "> a STAR story is exactly what a hiring manager catches on the follow-up.",
    "> If a real loop lands before the library is finished, this hour beats any",
    "> amount of new content.",
    "",
]
for rel, items in groups.items():
    lines += [f"## {rel}  ({len(items)} items)", ""]
    for ln, hint in items:
        lines.append(f"- [ ] line {ln}: {hint}")
    lines.append("")

lines += ["", "Fill each directly in the source file, replacing the whole",
          "`[CONFIRM: ...]` token with the real fact, then re-run the script",
          "until it reports 0 items.", ""]

OUT.parent.mkdir(exist_ok=True)
OUT.write_text("\n".join(lines), encoding="utf-8")
print(f"{OUT.name}: {total} open items across {len(groups)} files")
